### ISSUE TITLE
perl6 code needs to use v6

### ISSUE THREAD

**Issue by alexm** [vti/perltuts.com-tutorials#12]
In order to tell the eval server that it has to send the code to `perl6` the following line must be at the top of all code snippets:

```
use v6;
# perl6 code here...
```

**Comment by alexm** [comment]
Try the [Lexical variables](http://dev.perltuts.com/tutorials/perl-6-basics/lexical-variables) snippet in Perl6 tutorials that starts with:

```
sub seq($init) {
# ...
```

**Comment by alexm** [comment]
@ash you should take this into account for the Perl 6 tutorials.

**Comment by ash** [comment]
v6 is not needed in the programmes itself, thus can we made a special handling of the examples in the v6 part of the site?

**Comment by alexm** [comment]
Would something like this in the POD file work for you?

```
=head1 NAME

Perl 6 Basics

=head1 BEGIN

    use v6;

=head1 LANGUAGE

en

=head1 ABSTRACT

# ...
```

**Comment by ash** [comment]
I think something like that is great.

**Comment by alexm** [comment]
@ash, it seems that @vti is ahead of us and already provided a section that does just that :-)

```
=head1 PREAMBLE

    use v6;

```

I just tried it and works wonders. Just be careful to make it the first line in the preamble in case you need to add something else there.

**Comment by vti** [comment]
Yeah, everything was ready I guess :)

**Comment by alexm** [comment]
Sorry... Reopening until Perl 6 tutorials have the v6 preamble.

**Comment by ash** [comment]
updated

**Comment by alexm** [comment]
Perl 6 tutorials were updated and they are already online.
